# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "stylefsen"
license = "MIT"
licenselink = "https://github.com/eilefsen/stylefsen/blob/main/LICENSE"
description = "a (nearly) no-CSS, fast, minimalist Hugo theme forked from Masellum/nostyleplease."
homepage = "https://github.com/eilefsen/stylefsen"
tags = ["blog", "minimalist"]
features = []
min_version = "0.41.0"

[author]
  name = "Emma Eilefsen Glenna"
  homepage = "eilefsen.net"

# If porting an existing theme
[original]
  name = "riggraz"
  homepage = "Masellum.github.io"
  repo = "https://github.com/Masellum/hugo-theme-nostyleplease"
